config/routes.rb
Rails.application.routes.draw do
  get 'allstaff/home'

  get 'allstaff/select'

  get 'allstaff/portal'

  get 'allstaff/capabilities'

  root                                   'parks#index'
  # root                                   'main_pages#landing'
  get     'help'                      => 'main_pages#help'
  get     'about'                     => 'main_pages#about'
  get     'contact'                   => 'main_pages#contact'
  get     'landing'                   => 'main_pages#landing'
  get     'signup'                    => 'users#new'
  get     'login'                     => 'sessions#new'
  post    'login'                     => 'sessions#create'
  get     '/auth/:provider/callback'  => 'sessions#create'
  delete  'logout'                    => 'sessions#destroy'
  get     'parks_list'                => 'parks#parks_list'
  resources :users
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: [:new, :create, :edit, :update]

  resources :parks, only: [:index, :show] do
    resources :games, only: [:index, :show, :create, :destroy]
  end

  resources :game_participations,   only: [:update, :destroy]
  resources :messages,              only: [:create]
end

app/views/layouts/_desktop_menu.html.erb
<section class="navigation-section show-for-large-up contain-to-grid"
  id="desktop-top-bar">
  

  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <%= link_to root_path do %>
          <h1 class="title">League</h1>
        <% end %>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li>
          <a href="#">About</a>
        </li>
        <li>
          <a href="#">Help</a>
        </li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </section>
  </nav>
</section>

app/views/layouts/_mobile_menu.html.erb
<!-- Add class "hide-for-large-up" to nav to hide on desktop -->

<nav class="tab-bar hide-for-large-up" id="mobile-top-bar">
  <section class="left-small">
    <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
  </section>

  <section class="right tab-bar-section">
    <%= link_to root_path do %>
      <h1 class="title">League</h1>
    <% end %>
  </section>
</nav>

<aside class="left-off-canvas-menu">
  <ul class="off-canvas-list">
    <li>
      <label>
        <div class="row profile">
          <div class="small-6 columns">
            <%= image_tag( "brianScalabrine.jpeg",
                            alt: "Profile Picture",
                            class: "profile-pic") %>
          </div>
          <div class="small-6 columns">
            <h5 class="profile-name">Brian</h5>
          </div>
        </div>
      </label>
    </li>
    <li><a href=
      >Settings</a></li>
    <li><%= link_to "About",  about_path %></li>
    <li><%= link_to "Help",  help_path %></li>
    <li><%= link_to "Contact",  contact_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
    <% else %>
      <li><%= link_to "Log in", login_path %></li>
    <% end %>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <title><%= content_for?(:title) ? "#{yield(:title)} | Got Next" : "Got Next" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>


    <% yield :head %>

  </head>

  <body>

    <%= render 'shared/header' %>

    <% flash.each do |message_type, message| %>
      <%= render partial: '/shared/notification',
                 locals: {message_type: message_type, message: message} %>
    <% end %>

    <%= yield %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/layouts/marketing.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <title><%= content_for?(:title) ? "#{yield(:title)} | Got Next" : "Got Next" %></title>
    <%= stylesheet_link_tag    "marketing" %>
    <%= javascript_include_tag "marketing" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'main_pages/shared/marketing_header' %>

    <% flash.each do |message_type, message| %>
      <%= render partial: '/shared/notification',
                 locals: {message_type: message_type, message: message} %>
    <% end %>

    <%= yield %>

  </body>
</html>